"use client";
import { ChangeEvent, useMemo, useState } from "react";

type Page = "home" | "products" | "profit" | "pricing" | "campaign" | "analysis" | "settings";

type CalcResult = {
  estimatedProfit: number; margin: number; marketplaceFees: number; affiliateFee: number;
  breakEvenPrice: number; recommendedPrice: number; safeAffiliateRate: number; completeness: number;
  ruleVersion: string; ruleWarnings: string[]; lines: {code:string;label:string;amount:number;source:string}[];
};

const rp = (n:number) => new Intl.NumberFormat("id-ID", {style:"currency", currency:"IDR", maximumFractionDigits:0}).format(n);
const pct = (n:number) => `${(n*100).toFixed(1).replace(".",",")}%`;
const nav: {id:Page; label:string; icon:string}[] = [
  {id:"home",label:"Beranda",icon:"⌂"},{id:"products",label:"Produk",icon:"◇"},{id:"profit",label:"Cek Profit",icon:"◎"},
  {id:"pricing",label:"Cari Harga Jual",icon:"⌕"},{id:"campaign",label:"Simulasi Campaign",icon:"⚑"},{id:"analysis",label:"Analisis",icon:"▧"},{id:"settings",label:"Biaya & Pengaturan",icon:"⚙"}
];

export default function ProfitLabApp(){
  const [page,setPage]=useState<Page>("home");
  const [price,setPrice]=useState(129900); const [hpp,setHpp]=useState(65000); const [affiliate,setAffiliate]=useState(10);
  const [voucher,setVoucher]=useState(5); const [pack,setPack]=useState(2500); const [target,setTarget]=useState(20);
  const [result,setResult]=useState<CalcResult|null>(null); const [calcMsg,setCalcMsg]=useState("");
  const [campaign,setCampaign]=useState({discount:15,voucher:8,affiliate:15});
  const [importPreview,setImportPreview]=useState<any>(null); const [importName,setImportName]=useState("");

  const meta:Record<Page,[string,string]> = {
    home:["Beranda","Ringkasan kondisi profit dan tindakan prioritas."],products:["Produk","Kelola etalase, variasi, kategori, dan modal/HPP."],
    profit:["Cek Profit","Hitung keuntungan produk dengan rules marketplace terverifikasi."],pricing:["Cari Harga Jual","Temukan harga aman untuk target margin Anda."],
    campaign:["Simulasi Campaign","Uji diskon, voucher, dan affiliate sebelum diterapkan."],analysis:["Analisis","Fokus pada produk yang membutuhkan tindakan."],settings:["Biaya & Pengaturan","Atur brand, target margin, dan profil promo."]
  };

  async function calculate(customPrice=price){
    setCalcMsg("Menghitung…");
    const body={input:{marketplace:"shopee",sellerType:"regular",categoryId:"demo-category",calculationDate:new Date().toISOString().slice(0,10),unitPrice:customPrice,quantity:1,hppPerUnit:hpp,sellerDiscount:{type:"none"},sellerVoucher:{type:"percentage",rate:voucher/100},affiliateRate:affiliate/100,packagingPerOrder:pack,operationalPerOrder:0,ads:{type:"none"},otherCostPerOrder:0,targetMargin:target/100}};
    try{
      const r=await fetch("/api/calculate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}); const data=await r.json();
      if(!r.ok) throw new Error(data.error||"Gagal menghitung"); setResult(data.result); setCalcMsg(data.mode==="demo"?"Mode demo — aktifkan production rules untuk go-live.":"Rules produksi terverifikasi digunakan.");
    }catch(e){ setCalcMsg(e instanceof Error?e.message:"Gagal menghitung"); }
  }

  async function fileChange(e:ChangeEvent<HTMLInputElement>){ const f=e.target.files?.[0]; if(!f)return; setImportName(f.name); const text=await f.text();
    try{const r=await fetch("/api/import/preview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text})}); setImportPreview(await r.json());}catch{setImportPreview({error:"Preview gagal"});}
  }

  const campaignRisk=useMemo(()=>Math.min(99,Math.round(campaign.discount*1.6+campaign.voucher*1.1+campaign.affiliate*1.5)),[campaign]);
  const bad=Math.round(30+campaignRisk*1.35); const warn=Math.round(90+campaignRisk*1.5); const safe=1482-bad-warn;

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand-lockup side"><span className="brand-mark">◆</span><div><strong>ProfitLab</strong><small>Know your Real Profit</small></div></div>
      <nav>{nav.map(n=><button key={n.id} className={page===n.id?"active":""} onClick={()=>setPage(n.id)}><span>{n.icon}</span>{n.label}</button>)}</nav>
      <div className="sidebar-spacer"/><div className="business-card"><small>Business</small><strong>Sporty Brand</strong><span>▾</span></div>
      <div className="user-card"><span className="avatar">KA</span><div><strong>Kevin Aditama</strong><small>Owner</small></div><span>⋮</span></div>
    </aside>
    <main className="main-area">
      <header className="topbar"><div><h1>{meta[page][0]}</h1><p>{meta[page][1]}</p></div><div className="top-actions"><button className="ghost">15 Agu 2026</button><button className="icon-btn">♢</button></div></header>
      <div className="content">
        {page==="home"&&<Home onGo={setPage}/>} 
        {page==="products"&&<Products importPreview={importPreview} importName={importName} fileChange={fileChange}/>} 
        {page==="profit"&&<ProfitForm price={price} setPrice={setPrice} hpp={hpp} setHpp={setHpp} affiliate={affiliate} setAffiliate={setAffiliate} voucher={voucher} setVoucher={setVoucher} pack={pack} setPack={setPack} target={target} setTarget={setTarget} result={result} calculate={calculate} msg={calcMsg}/>} 
        {page==="pricing"&&<Pricing hpp={hpp} setHpp={setHpp} target={target} setTarget={setTarget} result={result} calculate={calculate}/>} 
        {page==="campaign"&&<Campaign values={campaign} setValues={setCampaign} risk={campaignRisk} safe={safe} warn={warn} bad={bad}/>} 
        {page==="analysis"&&<Analysis/>} {page==="settings"&&<Settings/>}
      </div>
    </main>
  </div>;
}

function Metric({label,value,sub,tone}:{label:string,value:string,sub:string,tone:string}){return <div className={`metric-card ${tone}`}><div className="metric-label">{label}</div><strong>{value}</strong><small>{sub}</small><span className="metric-orb">⌁</span></div>}
function Home({onGo}:{onGo:(p:Page)=>void}){return <>
  <div className="metrics"><Metric label="Total Variasi" value="1.482" sub="Semua marketplace" tone="purple"/><Metric label="Sehat" value="1.154" sub="77,9% dari total" tone="green"/><Metric label="Perlu Perhatian" value="214" sub="14,4% dari total" tone="amber"/><Metric label="Rugi" value="114" sub="7,7% dari total" tone="red"/></div>
  <div className="dashboard-grid top"><section className="panel chart-panel"><div className="panel-head"><div><h2>Trend Margin Rata-rata</h2><p>1–15 Agustus 2026</p></div><div className="big-kpi">18,7%<small>Margin rata-rata</small></div></div><svg viewBox="0 0 760 190" className="trend"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#8b5cf6" stopOpacity=".45"/><stop offset="1" stopColor="#8b5cf6" stopOpacity="0"/></linearGradient></defs><path d="M0,110 C70,42 100,120 165,104 S260,75 315,110 S390,77 450,94 S560,90 620,118 S700,92 760,100 L760,190 L0,190 Z" fill="url(#g)"/><path d="M0,110 C70,42 100,120 165,104 S260,75 315,110 S390,77 450,94 S560,90 620,118 S700,92 760,100" fill="none" stroke="#925cf6" strokeWidth="4"/></svg></section>
  <section className="panel marketplace-panel"><h2>Marketplace</h2><div className="donut"><div><strong>1.482</strong><small>Total Variasi</small></div></div><div className="legend"><span><i className="p"/>Shopee <b>1.085</b></span><span><i className="o"/>TikTok Shop <b>397</b></span></div></section></div>
  <div className="dashboard-grid bottom"><section className="panel"><h2>Yang Perlu Anda Periksa</h2><Alert tone="red" title="114 variasi berpotensi rugi" text="Segera periksa sebelum campaign" action="Lihat" onClick={()=>onGo("analysis")}/><Alert tone="amber" title="78 variasi di bawah target margin" text="Margin saat ini di bawah target" action="Lihat" onClick={()=>onGo("analysis")}/><Alert tone="blue" title="31 variasi belum memiliki modal" text="Lengkapi HPP agar kalkulasi akurat" action="Lengkapi" onClick={()=>onGo("products")}/><Alert tone="cyan" title="12 kategori perlu dikonfirmasi" text="Kategori memengaruhi biaya marketplace" action="Periksa" onClick={()=>onGo("products")}/></section>
  <section className="panel"><div className="panel-head"><h2>Margin Terendah</h2><button className="link" onClick={()=>onGo("analysis")}>Lihat Semua</button></div>{[["Running X — Black/44","4,2%"],["Sneaker Glow — White/42","5,1%"],["Sport Max — Red/40","6,3%"],["Runner Pro — Blue/41","6,8%"],["Daily Comfort — Black/43","7,1%"]].map((x,i)=><div className="product-mini" key={x[0]}><span className="shoe">{i+1}</span><div><strong>{x[0]}</strong><small>SKU: PL-{1030+i}</small></div><em>{x[1]}</em></div>)}</section>
  <section className="panel"><div className="panel-head"><h2>Simulasi Terakhir</h2><span className="pill green">Selesai</span></div><div className="simulation-box"><strong>Campaign Payday Agustus</strong><small>14 Agu 2026 • 14:30 WIB</small><div className="sim-kpis"><span><b>1.482</b>Total</span><span><b className="green-text">1.106</b>Aman</span><span><b className="amber-text">241</b>Tipis</span><span><b className="red-text">135</b>Rugi</span></div><button className="button primary" onClick={()=>onGo("campaign")}>Lihat Hasil Simulasi</button></div></section></div>
  <section className="panel quick"><h2>Aksi Cepat</h2><div className="quick-grid"><Quick title="Cek Profit" sub="Hitung satu produk" onClick={()=>onGo("profit")}/><Quick title="Cari Harga Jual" sub="Temukan harga aman" onClick={()=>onGo("pricing")}/><Quick title="Import Produk" sub="Upload data marketplace" onClick={()=>onGo("products")}/><Quick title="Simulasi Campaign" sub="Uji dampak promo" onClick={()=>onGo("campaign")}/></div></section>
</>}
function Alert({tone,title,text,action,onClick}:{tone:string,title:string,text:string,action:string,onClick:()=>void}){return <div className="alert-row"><span className={`alert-icon ${tone}`}>!</span><div><strong>{title}</strong><small>{text}</small></div><button className="small-button" onClick={onClick}>{action}</button></div>}
function Quick({title,sub,onClick}:{title:string,sub:string,onClick:()=>void}){return <button className="quick-card" onClick={onClick}><span className="qicon">◎</span><div><strong>{title}</strong><small>{sub}</small></div><span>→</span></button>}

function Products({importPreview,importName,fileChange}:{importPreview:any,importName:string,fileChange:(e:ChangeEvent<HTMLInputElement>)=>void}){return <>
  <div className="page-head"><div><h2>Product Workspace</h2><p>Etalase disederhanakan untuk user; perhitungan tetap berjalan sampai level variasi/SKU.</p></div><label className="button primary file-button">Import Produk<input type="file" accept=".csv,text/csv" onChange={fileChange}/></label></div>
  {importName&&<section className="panel import-preview"><div className="panel-head"><div><h2>Preview Import</h2><p>{importName}</p></div><span className="pill purple">{importPreview?.rowCount??0} baris</span></div>{importPreview?.error?<div className="inline-error">{importPreview.error}</div>:<><div className="mapping-grid">{Object.entries(importPreview?.detected||{}).map(([k,v])=><div key={k}><small>{k.replaceAll("_"," ")}</small><strong>{String(v||"Belum terdeteksi")}</strong></div>)}</div>{(importPreview?.warnings||[]).map((w:string)=><div className="inline-note" key={w}>{w}</div>)}</>}</section>}
  <section className="panel table-panel"><div className="panel-head"><div><h2>Produk & Variasi</h2><p>1.482 variasi dari 245 etalase</p></div><div className="filters"><button className="ghost">Semua Brand ▾</button><button className="ghost">Semua Marketplace ▾</button></div></div><div className="table-scroll"><table><thead><tr><th>Produk / Variasi</th><th>Brand</th><th>Marketplace</th><th>Kategori</th><th>Harga</th><th>HPP</th><th>Margin</th><th>Status</th></tr></thead><tbody>{[["Running X / Black 44","NORKHA","Shopee","Sepatu Olahraga",129900,72000,"4,2%","Rugi"],["Sneaker Glow / White 42","JOYSPORT","Shopee","Sneakers",149900,78000,"5,1%","Rugi"],["Runner Pro / Blue 41","FVNSPORT","TikTok","Sports Shoes",139900,69000,"18,4%","Perhatian"],["Daily Comfort / Black 43","NORKHA","Shopee","Casual Shoes",119900,52000,"24,8%","Sehat"]].map(r=><tr key={r[0] as string}><td><strong>{r[0]}</strong><small>SKU PL-{String(r[0]).slice(0,3).toUpperCase()}-01</small></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td>{rp(r[4] as number)}</td><td>{rp(r[5] as number)}</td><td>{r[6]}</td><td><span className={`pill ${r[7]==="Sehat"?"green":r[7]==="Rugi"?"red":"amber"}`}>{r[7]}</span></td></tr>)}</tbody></table></div></section>
</>}

function ProfitForm(p:any){return <div className="two-col"><section className="panel form-panel"><div className="eyebrow">KALKULATOR PRODUK</div><h2>Cek Profit</h2><p>Field inti dibuat minimal. Detail tambahan tersedia bila dibutuhkan.</p><div className="form-grid"><label>Marketplace<select><option>Shopee</option><option>TikTok Shop</option></select></label><label>Kategori<select><option>Sepatu Olahraga</option><option>Sneakers</option></select></label><label>Harga Jual<input type="number" value={p.price} onChange={(e:any)=>p.setPrice(+e.target.value)}/></label><label>Modal / HPP<input type="number" value={p.hpp} onChange={(e:any)=>p.setHpp(+e.target.value)}/></label><div className="split-fields"><label>Affiliate %<input type="number" value={p.affiliate} onChange={(e:any)=>p.setAffiliate(+e.target.value)}/></label><label>Voucher Seller %<input type="number" value={p.voucher} onChange={(e:any)=>p.setVoucher(+e.target.value)}/></label></div><div className="split-fields"><label>Packaging<input type="number" value={p.pack} onChange={(e:any)=>p.setPack(+e.target.value)}/></label><label>Target Margin %<input type="number" value={p.target} onChange={(e:any)=>p.setTarget(+e.target.value)}/></label></div><button className="button primary" onClick={()=>p.calculate()}>Hitung Profit</button>{p.msg&&<div className="inline-note">{p.msg}</div>}</div></section><section className="panel result-panel">{!p.result?<div className="empty-state"><span>◎</span><h2>Hasil akan muncul di sini</h2><p>ProfitLab akan menampilkan profit, margin, harga aman, dan sumber biaya.</p></div>:<Result result={p.result}/>}</section></div>}
function Result({result}:{result:CalcResult}){return <><div className="eyebrow">ESTIMASI KEUNTUNGAN</div><div className="profit-number">{rp(result.estimatedProfit)}</div><div className="result-status"><span className={`pill ${result.margin>=.2?"green":"amber"}`}>Margin {pct(result.margin)}</span><span>Kelengkapan {result.completeness}%</span></div><div className="result-cards"><div><small>Harga minimal</small><strong>{rp(result.breakEvenPrice)}</strong></div><div><small>Harga target</small><strong>{rp(result.recommendedPrice)}</strong></div><div><small>Affiliate aman</small><strong>{pct(result.safeAffiliateRate)}</strong></div></div><h3>Bagaimana angka ini dihitung?</h3><div className="calc-lines">{result.lines.filter(l=>Math.abs(l.amount)>0).map(l=><div key={l.code}><span><b>{l.label}</b><small>{l.source}</small></span><strong className={l.amount<0?"negative":""}>{l.amount<0?"−":""}{rp(Math.abs(l.amount))}</strong></div>)}</div><div className="rule-foot">Rule version: <b>{result.ruleVersion}</b></div>{result.ruleWarnings.map(w=><div className="inline-warning" key={w}>{w}</div>)}</>}

function Pricing({hpp,setHpp,target,setTarget,result,calculate}:any){return <div className="two-col"><section className="panel form-panel"><div className="eyebrow">SAFE PRICING</div><h2>Cari Harga Jual</h2><p>Masukkan modal dan target margin. ProfitLab mencari harga yang memenuhi target.</p><div className="form-grid"><label>Modal / HPP<input type="number" value={hpp} onChange={(e:any)=>setHpp(+e.target.value)}/></label><label>Target Margin<input type="number" value={target} onChange={(e:any)=>setTarget(+e.target.value)}/></label><button className="button primary" onClick={()=>calculate(150000)}>Hitung Harga Aman</button></div></section><section className="panel result-panel"><div className="eyebrow">REKOMENDASI</div><div className="price-recommend">{result?rp(result.recommendedPrice):"Rp—"}</div><p>Harga yang disarankan untuk mempertahankan target margin {target}% berdasarkan struktur biaya yang aktif.</p>{result&&<div className="result-cards"><div><small>Jangan jual di bawah</small><strong>{rp(result.breakEvenPrice)}</strong></div><div><small>Affiliate maksimum</small><strong>{pct(result.safeAffiliateRate)}</strong></div><div><small>Rule</small><strong>{result.ruleVersion}</strong></div></div>}</section></div>}

function Campaign({values,setValues,risk,safe,warn,bad}:any){const row=(k:string,label:string,max:number)=><div className="slider-row"><div><strong>{label}</strong><small>{values[k]}%</small></div><input type="range" min="0" max={max} value={values[k]} onChange={e=>setValues({...values,[k]:+e.target.value})}/></div>;return <div className="two-col campaign-layout"><section className="panel form-panel"><div className="eyebrow">CAMPAIGN LAB</div><h2>Coba Skenario</h2><p>Uji profil promo sebelum diterapkan ke produk.</p>{row("discount","Diskon",40)}{row("voucher","Voucher Seller",25)}{row("affiliate","Affiliate",30)}<div className="safe-zone"><span>Intensitas promo</span><strong>{risk}/100</strong><div><i style={{width:`${risk}%`}}/></div></div></section><section className="panel result-panel"><div className="panel-head"><div><div className="eyebrow">SIMULASI</div><h2>1.482 variasi dianalisis</h2></div><span className="pill purple">Live</span></div><div className="campaign-kpis"><div><b>{safe.toLocaleString("id-ID")}</b><small>Aman</small></div><div><b>{warn.toLocaleString("id-ID")}</b><small>Margin tipis</small></div><div><b>{bad.toLocaleString("id-ID")}</b><small>Berpotensi rugi</small></div></div><div className="guard-card"><span>PROFIT GUARD</span><h3>{bad>150?"Campaign terlalu agresif":"Campaign masih terkendali"}</h3><p>{bad} variasi perlu diperiksa. Prioritaskan SKU dengan margin dasar rendah sebelum mengaktifkan campaign.</p><div className="guard-bars"><i className="good" style={{width:`${safe/14.82}%`}}/><i className="warn" style={{width:`${warn/14.82}%`}}/><i className="bad" style={{width:`${bad/14.82}%`}}/></div></div></section></div>}

function Analysis(){return <><div className="metrics"><Metric label="Rugi" value="114" sub="Prioritas tinggi" tone="red"/><Metric label="Di bawah Target" value="78" sub="Perlu optimasi" tone="amber"/><Metric label="Tanpa HPP" value="31" sub="Data belum lengkap" tone="purple"/><Metric label="Kategori Perlu Cek" value="12" sub="Fee belum final" tone="green"/></div><section className="panel table-panel"><h2>Prioritas Tindakan</h2><div className="table-scroll"><table><thead><tr><th>Produk</th><th>Masalah</th><th>Dampak</th><th>Saran ProfitLab</th><th></th></tr></thead><tbody><tr><td>Running X — Black/44</td><td><span className="pill red">Margin 4,2%</span></td><td>Berisiko rugi saat promo</td><td>Naikkan harga / turunkan affiliate</td><td><button className="small-button">Perbaiki</button></td></tr><tr><td>Sneaker Glow — White/42</td><td><span className="pill amber">Affiliate tinggi</span></td><td>Margin turun signifikan</td><td>Simulasikan affiliate 8%</td><td><button className="small-button">Simulasikan</button></td></tr></tbody></table></div></section></>}
function Settings(){return <div className="two-col"><section className="panel form-panel"><div className="eyebrow">BRAND DEFAULT</div><h2>NORKHA</h2><div className="form-grid"><label>Target Margin<input defaultValue="20%"/></label><label>Affiliate Default<input defaultValue="10%"/></label><label>Voucher Seller Default<input defaultValue="5%"/></label><button className="button primary">Simpan Pengaturan</button></div></section><section className="panel form-panel"><div className="eyebrow">PROFIT PROFILE</div><h2>Profil Promo</h2>{[["Normal","Diskon 0% · Voucher 5% · Affiliate 10%"],["Payday","Diskon 10% · Voucher 10% · Affiliate 12%"],["Mega Campaign","Diskon 20% · Voucher 10% · Affiliate 15%"]].map(x=><div className="profile-row" key={x[0]}><span className="qicon">◆</span><div><strong>{x[0]}</strong><small>{x[1]}</small></div><button className="small-button">Edit</button></div>)}</section></div>}
